//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unleashing_Potential
{
    public partial class WebForm6
    {
        /// <summary>
        /// lblUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUserName;

        /// <summary>
        /// litTownship control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTownship;

        /// <summary>
        /// litJoined control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litJoined;

        /// <summary>
        /// litTotalBookings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalBookings;

        /// <summary>
        /// litPendingBookings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPendingBookings;

        /// <summary>
        /// litActiveBookings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litActiveBookings;

        /// <summary>
        /// litTotalSpent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalSpent;

        /// <summary>
        /// rptRecentBookings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRecentBookings;

        /// <summary>
        /// pnlNoBookings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoBookings;

        /// <summary>
        /// lblBasketCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBasketCount;
    }
}
